export function utcNow() {
  return new Date().toISOString();
}

export function buildDefaultState() {
  return {
    schema_version: "1.0",
    feature_slug: "",
    route: "",
    work_intent: "delivery",
    risk: "normal",
    run_style: "guided",
    orchestration_strategy: "",
    active_skill: "using-beer",
    context_stage: "none",
    seed_path: ".beer/seed/",
    context_path: "",
    context_confidence: 0,
    phase: "idle",
    phase_number: 0,
    current_phase_name: "",
    current_slice: "",
    slice_count: 0,
    planned_workers: 0,
    prep_depth: "",
    execution_target: "",
    contract_verified: false,
    validation_status: "",
    validator_status: "",
    spike_status: "",
    swarm_status: "",
    active_work_item: "",
    tdd_required: false,
    tdd_status: "not-required",
    tdd_evidence_path: "",
    execution_evidence_path: "",
    verification_status: "not-run",
    gitnexus_refresh_status: "",
    code_quantity_status: "",
    pattern_status: "",
    review_quality_status: "",
    review_route: "",
    review_status: "",
    open_findings_count: 0,
    compounding_route: "",
    learnings_file: "",
    critical_promotions: 0,
    knowledge_base_refresh_status: "",
    closeout_ready: false,
    next_handoff: "",
    epic_id: "",
    approved_gates: {
      context: false,
      phase_plan: false,
      execution: false,
      review: false,
    },
    active_beads: [],
    active_workers: [],
    auto_accept: {
      enabled: false,
      planning: false,
      validating: false,
      swarming: false,
      reviewing: false,
      compounding: false,
    },
    blockers: [],
    last_updated: utcNow(),
  };
}

export function buildDefaultConfig() {
  return {
    schema_version: "1.0",
    ecosystem: "beer",
    version: "1.0.0",
    features: {
      context_intake: true,
      graph_explore: true,
      codex_hooks: true,
    },
    defaults: {
      risk: "normal",
      run_style: "guided",
      orchestration_strategy: "auto",
      max_workers: 3,
      context_threshold: 0.65,
    },
    auto_accept: {
      enabled: false,
      planning: false,
      validating: false,
      swarming: false,
      reviewing: false,
      compounding: false,
    },
    dependencies: {
      task_tracker: "beads",
      graph_engine: "gitnexus",
    },
    models: {
      orchestrator: {
        model: "gpt-5.4",
        reasoning_effort: "high",
      },
      coding: {
        model: "gpt-5.3-codex",
        reasoning_effort: "high",
      },
      research_synthesis: {
        model: "gpt-5.4-mini",
        reasoning_effort: "medium",
      },
    },
  };
}

export function buildDefaultStateMd() {
  return [
    "# Beer State",
    "",
    "Current: idle",
    "Feature: (none)",
    "Route: (none)",
    "Work intent: delivery",
    "Risk: normal",
    "Run style: guided",
    "Orchestration: (none)",
    "Context: none",
    "Context path: (none)",
    "Phase: idle",
    "Current phase: (none)",
    "Current slice: (none)",
    "Slices: 0",
    "Planned workers: 0",
    "Gate approvals: context=no, phase_plan=no, execution=no, review=no",
    "Contract verified: no",
    "Validation: (none)",
    "Validator: (none)",
    "Execution target: (none)",
    "TDD required: no",
    "TDD status: not-required",
    "TDD evidence: (none)",
    "Execution evidence: (none)",
    "Verification: not-run",
    "GitNexus refresh: (none)",
    "Code quantity: (none)",
    "Pattern: (none)",
    "Review quality: (none)",
    "Review: (none)",
    "Generated Docs refresh: (none)",
    "Closeout ready: no",
    "Next handoff: (none)",
    "",
    "Artifacts:",
    "",
    "- (none)",
    "",
    "Last updated: " + utcNow().slice(0, 10),
    "",
  ].join("\n");
}
