export function printHelp() {
  process.stdout.write(
    [
      "Usage: beer <command> [options]",
      "",
      "Commands:",
      "  init            Onboard a repo with Beer workflow files",
      "  update          Update the global Beer package from GitHub",
      "  refresh         Refresh the managed Beer files in a repo",
      "  uninstall       Remove Beer-managed files from a repo",
      "  approve <gate>  Record a manual gate approval in guided workflows",
      "  install <tool>  Install a Beer tool (gitnexus or beads)",
      "  index           Refresh the current repo's GitNexus index",
      "  check-tools     Show which Beer tools are installed or missing",
      "  status          Show Beer status for a repo",
      "  flow-guard      Check whether Beer currently allows a non-trivial edit",
      "  review-guard    Check review-time code quantity and pattern spread",
      "  closeout-guard  Check whether Beer closeout obligations are complete",
      "  auto-accept    Check whether a Beer gate may auto-advance",
      "  dependencies    Show Beer dependency report for the current bundle",
      "  planning-gate   Check whether planning may proceed",
      "",
      "Install Beer globally:",
      "  npm install -g github:Huy-04/beer-skills",
      "  beer --help",
      "",
      "Init options:",
      "  --repo-root <path>   Target repo root (default: cwd/git root)",
      "",
      "Install options:",
      "  --dry-run-tools     Print the install command without executing it",
      "  --path <file>       Target file path for flow-guard (repeatable)",
      "  --trivial           Explicit trivial-task bypass for flow-guard",
      "  --knowledge-base    Record a closeout decision: not-needed, approved, declined, or refreshed",
      "",
      "Shared options:",
      "  --yes               Skip the uninstall confirmation prompt",
      "  --route <name>       Planning route for planning-gate: feature or small-fix",
      "  --gate <name>        Gate for auto-accept: planning, validating, swarming, reviewing, or compounding",
      "                     Approval targets for approve: context, phase-plan, execution, or review",
      "  --json              Print JSON where supported",
    ].join("\n"),
  );
}
